### ISSUE TITLE
Improvement: Using Argparse 

### ISSUE THREAD

**Issue by JSchwehn** [fallenbeck/tt#6]
Instead accessing `argc` directly the `Argparse` lib could be used to gain a bit more flexibility in parsing command parameters.

See https://docs.python.org/3/howto/argparse.html

**Comment by fallenbeck** [comment]
I am pretty sure not switching to argparse soon.
The reason is that this script is initialized everytime when it is called. Therefore I want the script to be as slim as possible. Furthermore, the use of argparse would not add any benefits.
But I am open for discussions.

**Comment by fallenbeck** [comment]
Since this would result in a complete refactoring of `tt` I have no actual plans to start that but I also feel the need that some sime it should be done.
