### ISSUE TITLE
Feature: Add a comment when starting a project

### ISSUE THREAD

**Issue by JSchwehn** [fallenbeck/tt#9]
It would be nice if a comment can be provided when project is started. This comment should belong to the current tracking entry. I think, if a pause/resume feature is in place, the comment should be transported over to the resumed project.

**Comment by fallenbeck** [comment]
To be honest I do not yet know if I want to implement such a functionality.

If so, I rather would decouple the ability to add comments to a certain running tracker from starting this tracker allowing users to add comments to a later point in time when the stumble over something they want to mention in a time keeping software.

However, adding comments to a time tracker is somehow a bit outside the focus of a time tracking software. At least I need to get a feeling for that.
This would require the data file format to change again.

**Comment by fallenbeck** [comment]
Available in 0.15
